# ---------------------------------------------------------------------- #
#                  EXAMPLE SECRETS - RENAME TO .toml                     #
# ---------------------------------------------------------------------- #
# This file contains your secret credentials.
# Copy this to 'secrets.toml' and fill in your values.
# DO NOT COMMIT 'secrets.toml' TO GIT.

# Your Discord bot's unique token.
discord_bot_token = "YOUR_DISCORD_BOT_TOKEN_HERE"
# The ID of the channel where the RuneLite plugin sends messages.
discord_data_channel_id = "YOUR_DATA_CHANNEL_ID_HERE"
# The ID of the channel where Wise Old Man posts name change updates.
discord_WOM_updates_channel_id = "YOUR_WOM_UPDATES_CHANNEL_ID_HERE"
# The ID of the channel where the PB embeds will be posted.
discord_pb_channel_id = "YOUR_PB_CHANNEL_ID_HERE"
# The webhook URL for posting script summaries.
discord_webhook_url = "YOUR_WEBHOOK_URL_HERE"

[api_settings]
# A descriptive User-Agent is required by some APIs (like the OSRS Wiki prices API).
# It helps them identify your application. Please set this to something unique.
# Per the API documentation, this should identify your tool and a contact method.
# Example: user_agent = "My Clan's Dashboard - Discord: myusername#1234"
user_agent = ""